
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Loan_calculation extends javax.swing.JFrame {

    /**
     * Creates new form Loan_calculation
     */
    public Loan_calculation() {
        initComponents();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        Date d = new Date();
        date.setText(sdf.format(d));
        
        cbLoadData("customer","nic", nic_combo);
        AutoCompleteDecorator.decorate(nic_combo);
        
        cbLoadData("loan","date", date_comb);
        AutoCompleteDecorator.decorate(date_comb);
   
        try {
            
            ResultSet rs = dbcon.SEARCH("SELECT * FROM loan");
            while(rs.next()){
                
                String id = rs.getString("nic");
                String na = rs.getString("name");
                String dat = rs.getString("date");
                String am = rs.getString("amount");
                String ir = rs.getString("interest_rate");
                String in = rs.getString("installments");
                String ia = rs.getString("installment_amount");
                String oa = rs.getString("outstanding_amount");
                
                Vector v = new Vector();
                v.add(id);
                v.add(na);
                v.add(dat);
                v.add(am);
                v.add(ir);
                v.add(in);
                v.add(ia);
                v.add(oa);
               
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.addRow(v);
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dayIncome = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        install = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        installAmmount = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        outsAmount = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        full_totalAmount = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        dayLoanAmmount = new javax.swing.JLabel();
        full_totalOutsAmmount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        report = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        payAmount1 = new javax.swing.JTextField();
        combobox = new javax.swing.JComboBox<>();
        nic_combo = new javax.swing.JComboBox<>();
        name = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calculation = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        date_comb = new javax.swing.JComboBox<>();
        loadAll = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tb_report = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(1300, 1000));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 1000));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOAN NO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ANNUAL IR %");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INSTALLMENTS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INSTALLMENTS AMMOUNT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL AMMOUNT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SEARCH");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PAY AMMOUNT");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, -1, -1));

        dayIncome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dayIncome.setForeground(new java.awt.Color(255, 255, 255));
        dayIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayIncome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(dayIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 220, 30));

        date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("0000/00/00");
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 180, 40));

        search.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 30));

        am.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        am.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        am.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amKeyReleased(evt);
            }
        });
        jPanel1.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 200, 30));

        rate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateActionPerformed(evt);
            }
        });
        rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rateKeyReleased(evt);
            }
        });
        jPanel1.add(rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 200, 30));

        install.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        install.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        install.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                installKeyReleased(evt);
            }
        });
        jPanel1.add(install, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 200, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DATE");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 50, 20));

        installAmmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        installAmmount.setForeground(new java.awt.Color(255, 255, 255));
        installAmmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        installAmmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(installAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 200, 30));

        totalAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalAmount.setForeground(new java.awt.Color(255, 255, 255));
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 200, 30));

        outsAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        outsAmount.setForeground(new java.awt.Color(255, 255, 255));
        outsAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outsAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(outsAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 780, 200, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("OUTSTANDING AMMOUNT");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("AMOUNT");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        add.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        add.setText("ADD");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 890, 140, 50));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("NIC");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("TOTAL AMMOUNT");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TOTAL OUTSTANDING AMOUNT");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, -1, 20));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("DAY INCOME");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        full_totalAmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        full_totalAmount.setForeground(new java.awt.Color(255, 255, 255));
        full_totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        full_totalAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(full_totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 220, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("DAY LOAN AMMOUNT");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        dayLoanAmmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dayLoanAmmount.setForeground(new java.awt.Color(255, 255, 255));
        dayLoanAmmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dayLoanAmmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(dayLoanAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 220, 30));

        full_totalOutsAmmount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        full_totalOutsAmmount.setForeground(new java.awt.Color(255, 255, 255));
        full_totalOutsAmmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        full_totalOutsAmmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(full_totalOutsAmmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 220, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 10, 860));

        report.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        report.setForeground(new java.awt.Color(0, 0, 0));
        report.setText("REPORT");
        report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 120, -1));

        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setText("REGISTER");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 890, 140, 50));

        delete2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delete2.setForeground(new java.awt.Color(204, 51, 0));
        delete2.setText("LOGOUT");
        delete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        jPanel1.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 890, 120, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 750, 270));

        payAmount1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        payAmount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payAmount1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                payAmount1KeyReleased(evt);
            }
        });
        jPanel1.add(payAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 720, 200, 30));

        combobox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        combobox.setForeground(new java.awt.Color(255, 255, 255));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        combobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        combobox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 80, -1));

        nic_combo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nic_combo.setForeground(new java.awt.Color(255, 255, 255));
        nic_combo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        nic_combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nic_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nic_comboMouseClicked(evt);
            }
        });
        nic_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic_comboActionPerformed(evt);
            }
        });
        jPanel1.add(nic_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 200, -1));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 200, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "NAME", "DATE", "AMMOUNT", "RATE", "INS", "IN AM", "OUT_AM"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 750, 150));

        calculation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        calculation.setForeground(new java.awt.Color(255, 51, 51));
        calculation.setText("CALCULATION");
        calculation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        calculation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformed(evt);
            }
        });
        jPanel1.add(calculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 270, 220, 30));

        clear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("CLEAR");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 830, 90, 30));

        date_comb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date_comb.setForeground(new java.awt.Color(255, 255, 255));
        date_comb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        date_comb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        date_comb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_combMouseClicked(evt);
            }
        });
        date_comb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_combActionPerformed(evt);
            }
        });
        jPanel1.add(date_comb, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 180, 30));

        loadAll.setBackground(new java.awt.Color(255, 255, 255));
        loadAll.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loadAll.setForeground(new java.awt.Color(255, 255, 255));
        loadAll.setText("ALL");
        loadAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        loadAll.setContentAreaFilled(false);
        loadAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadAllActionPerformed(evt);
            }
        });
        jPanel1.add(loadAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, 50, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "TOTAL AMMOUNTS", "TOTAL OUTS", "DAY INCOME", "DAY LOAN"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 820, 750, 110));

        tb_report.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tb_report.setForeground(new java.awt.Color(0, 0, 0));
        tb_report.setText("TB REPORT");
        tb_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_reportActionPerformed(evt);
            }
        });
        jPanel1.add(tb_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 760, -1, -1));

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("REFRESH");
        refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        refresh.setContentAreaFilled(false);
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 760, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
       // int loanNumber = Integer.parseInt(loan_no.getText()); 
       int loanNumber = Integer.parseInt(combobox.getSelectedItem().toString());

        int maxLoans = 2;
        double firstLoanLimit = 20000.00;
        int currentLoans = Integer.parseInt(am.getText()); // Replace with a mechanism to track current loans
        
        if (loanNumber > maxLoans) {
            JOptionPane.showMessageDialog(this,"You can get two times get loans","ERROR!",JOptionPane.ERROR_MESSAGE);
        }else{             
            if (loanNumber == 1) {
                if(currentLoans<=firstLoanLimit){
                
                 }else{
                    JOptionPane.showMessageDialog(this, "First Loan is Must lower than Ru.20 000","DONE",JOptionPane.INFORMATION_MESSAGE);
                    am.setText(null);
                    rate.setText(null);
                    install.setText(null);
                    installAmmount.setText(null);
                    totalAmount.setText(null);
                    payAmount1.setText(null);
                    outsAmount.setText(null);
            }
            }
                try {
                    String ni = nic_combo.getSelectedItem().toString();
                    String na = name.getText();
                     
                    String dat = date.getText();
                    String ca = am.getText();
                    String ty = rate.getText();
                    String ba = install.getText();
                    String dis = installAmmount.getText();
                    //String cus = totalAmount.getText();
                    //String pa = payAmount1.getText();
                    String oa = outsAmount.getText();
            
                    dbcon.IUD("INSERT INTO loan (`nic`,`name`,`date`,`amount`,`interest_rate`,`installments`,`installment_amount`,`outstanding_amount`) VALUES ('"+ni+"','"+na+"','"+dat+"','"+ca+"','"+ty+"','"+ba+"','"+dis+"','"+oa+"')");
                    JOptionPane.showMessageDialog(this, "Transaction Details Added Successfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
                    am.setText(null);
                    rate.setText(null);
                    install.setText(null);
                    installAmmount.setText(null);
                    totalAmount.setText(null);
                    payAmount1.setText(null);
                    outsAmount.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
            }
        

        
    }//GEN-LAST:event_addActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        
        try {
            String dat = this.date.getText();
            String full_am = full_totalAmount.getText();
            String bill = full_totalOutsAmmount.getText();
            String cus = dayIncome.getText();
            String total = dayLoanAmmount.getText();
           
            // Bill create
            
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "................................INTEREST COMPANY............................................" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "................................Galle Dangedara..........................................." + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "..................................0703927563.............................................." + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "..............................lak1701201@gmail.com........................................" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... DATE                           :- "+dat+"" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... Full Ammount                   :- "+full_am+"" + "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... Full Total Outstanding Ammount :- "+bill+"" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... Day Income                     :- "+cus+"" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t" + "....... Day Loan Ammount               :- "+total+"" + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n"+ "\n"+ "\n");
                       
            
            
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######"+"\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"....................................SIGNATURE..............................................." + "\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "*************************************************************************************************"+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"....................................THANK YOU..............................................."+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ "\t"+"...................................COME AGAIN..............................................."+"\n"+ "\n");
            jTextArea1.setText(jTextArea1.getText()+ " ..........  LAKSHITHA MADUSHAN @ SOFTWARE ENGINEER - JAVA DEVELOPER!!! ALL RIGHT (C)  .........."+"\n"+"\n");
            jTextArea1.setText(jTextArea1.getText()+ "#############**********################********#############*******###############........#######");
            
            jTextArea1.print();
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_reportActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Register r = new Register();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_delete2ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try {
         
         ResultSet rs = dbcon.SEARCH("SELECT * FROM loan WHERE `nic` = '"+search.getText()+"'");
         
         if(rs.next()){
            
                String id = rs.getString("nic");
                String na = rs.getString("name");
                String add = rs.getString("amount");
                String ph = rs.getString("outstanding_amount");
                
                //nic.setText(id);
                name.setText(na);
                nic_combo.setSelectedItem(id);
                outsAmount.setText(ph);
                am.setText(add);
                
                
           
         }
         //name.setText(null);
         
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchKeyReleased

    private void amKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amKeyReleased
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_EQUALS | evt.getKeyCode() == KeyEvent.VK_MINUS | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK ) {
            am.setEditable(true);
        }else{
            am.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,shift,Plus or Minus keys","ERROR!",JOptionPane.ERROR_MESSAGE);
            am.setText(null);
            am.grabFocus();
           
        }
    }//GEN-LAST:event_amKeyReleased

    private void rateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rateKeyReleased
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_EQUALS | evt.getKeyCode() == KeyEvent.VK_MINUS | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK | evt.getKeyCode() == KeyEvent.VK_PERIOD ) {
            rate.setEditable(true);
        }else{
            rate.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,shift,Plus or Minus keys","ERROR!",JOptionPane.ERROR_MESSAGE);
            rate.setText(null);
            rate.grabFocus();
        }
    }//GEN-LAST:event_rateKeyReleased

    private void rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateActionPerformed

    private void installKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_installKeyReleased
        // TODO add your handling code here:
            int ina = Integer.parseInt(install.getText());
         
            if( ina<=12){
                double amm = Double.parseDouble(am.getText());
                double r = Double.parseDouble(rate.getText());
                double newr = r/100;
                int in = Integer.parseInt(install.getText());
        
                double cal = amm * newr;
                double sum = (cal + amm)/in ;
                  
                installAmmount.setText(String.valueOf(sum));
               
                double total = sum * in;
                totalAmount.setText(String.valueOf(total));
            }else{
                JOptionPane.showMessageDialog(this, "Number of installments should be in 12 months","DONE",JOptionPane.INFORMATION_MESSAGE);
            }

        
            
            
    }//GEN-LAST:event_installKeyReleased

    private void payAmount1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payAmount1KeyReleased
        // TODO add your handling code here:
                double amm = Double.parseDouble(totalAmount.getText());
                double r = Double.parseDouble(payAmount1.getText());
               
                double cal = amm - r;
                
                outsAmount.setText(String.valueOf(cal));
        
    }//GEN-LAST:event_payAmount1KeyReleased

    private void nic_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nic_comboMouseClicked
    
    }//GEN-LAST:event_nic_comboMouseClicked

    private void nic_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic_comboActionPerformed
        // TODO add your handling code here:
        
        try {
            String item = nic_combo.getSelectedItem().toString();
            ResultSet rs = dbcon.SEARCH("SELECT * FROM customer WHERE `nic` = '"+item+"'");
            rs.next();
            String brand = rs.getString("name");

            name.setText(brand);
            
        
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_nic_comboActionPerformed

    private void calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformed
        // TODO add your handling code here:
        
        double sum =0;
        for(int i=0;i < jTable1.getRowCount();i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 6).toString());
        }
        dayIncome.setText(String.valueOf(sum));
        
        double sum1 =0;
        for(int i=0;i < jTable1.getRowCount();i++){
            sum1 = sum1 + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        full_totalAmount.setText(String.valueOf(sum1));
        
        double sum3 =0;
        for(int i=0;i < jTable1.getRowCount();i++){
            sum3 = sum3 + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        dayLoanAmmount.setText(String.valueOf(sum3));
        
        double sum4 =0;
        for(int i=0;i < jTable1.getRowCount();i++){
            sum4 = sum4 + Double.parseDouble(jTable1.getValueAt(i, 7).toString());
        }
        full_totalOutsAmmount.setText(String.valueOf(sum4));
        
        
                    String dat = date_comb.getSelectedItem().toString();
                    String ca = full_totalAmount.getText();
                    String ty = full_totalOutsAmmount.getText();
                    String ba = dayIncome.getText();
                    String dis = dayLoanAmmount.getText();
        
            DefaultTableModel dtm =(DefaultTableModel)jTable2.getModel();
            dtm.insertRow(dtm.getRowCount(), new Object[]{dat, ca , ty, ba, dis } );
        
    }//GEN-LAST:event_calculationActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
                    am.setText(null);
                    rate.setText(null);
                    install.setText(null);
                    installAmmount.setText(null);
                    totalAmount.setText(null);
                    payAmount1.setText(null);
                    outsAmount.setText(null);
                    name.setText(null);
                    search.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void date_combMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_combMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_date_combMouseClicked

    private void date_combActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_combActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = dbcon.SEARCH("SELECT * FROM loan WHERE `date` = '"+String.valueOf(date_comb.getSelectedItem())+"'");
            while(rs.next()){
                String id = rs.getString("nic");
                String na = rs.getString("name");
                String dat = rs.getString("date");
                String am = rs.getString("amount");
                String ir = rs.getString("interest_rate");
                String in = rs.getString("installments");
                String ia = rs.getString("installment_amount");
                String oa = rs.getString("outstanding_amount");
                
                Vector v = new Vector();
                v.add(id);
                v.add(na);
                v.add(dat);
                v.add(am);
                v.add(ir);
                v.add(in);
                v.add(ia);
                v.add(oa);
               
                
                dtm.addRow(v);
                
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_date_combActionPerformed

    private void loadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadAllActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet rs = dbcon.SEARCH("SELECT * FROM loan");
            while(rs.next()){
                String id = rs.getString("nic");
                String na = rs.getString("name");
                String dat = rs.getString("date");
                String am = rs.getString("amount");
                String ir = rs.getString("interest_rate");
                String in = rs.getString("installments");
                String ia = rs.getString("installment_amount");
                String oa = rs.getString("outstanding_amount");
                
                Vector v = new Vector();
                v.add(id);
                v.add(na);
                v.add(dat);
                v.add(am);
                v.add(ir);
                v.add(in);
                v.add(ia);
                v.add(oa);
               
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_loadAllActionPerformed

    private void tb_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_reportActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("........LAKSHITHA SOFTWARE JAVA (C) All Rights........"+"\n"
                +"\t" + "................................DIGIMAX MOBILE............................................" + "\n"+
                "\t" + "................................Galle Dangedara..........................................." + "\n"+
                "\t" + "..................................0703927563.............................................." + "\n"+
                "\t" + "..............................lak1701201@gmail.com........................................" + "\n");
        MessageFormat footer = new MessageFormat("...................Thank You!!!.......................");
        
        try {
            jTable2.print(JTable.PrintMode.NORMAL,header,footer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tb_reportActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        try {
            ResultSet rs = dbcon.SEARCH("SELECT * FROM loan");
            while(rs.next()){
                String id = rs.getString("nic");
                String na = rs.getString("name");
                String dat = rs.getString("date");
                String am = rs.getString("amount");
                String ir = rs.getString("interest_rate");
                String in = rs.getString("installments");
                String ia = rs.getString("installment_amount");
                String oa = rs.getString("outstanding_amount");
                
                Vector v = new Vector();
                v.add(id);
                v.add(na);
                v.add(dat);
                v.add(am);
                v.add(ir);
                v.add(in);
                v.add(ia);
                v.add(oa);
               
                
                dtm.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan_calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField am;
    private javax.swing.JButton calculation;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel date;
    private javax.swing.JComboBox<String> date_comb;
    private javax.swing.JLabel dayIncome;
    private javax.swing.JLabel dayLoanAmmount;
    private javax.swing.JButton delete2;
    private javax.swing.JLabel full_totalAmount;
    private javax.swing.JLabel full_totalOutsAmmount;
    private javax.swing.JTextField install;
    private javax.swing.JLabel installAmmount;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadAll;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> nic_combo;
    private javax.swing.JLabel outsAmount;
    private javax.swing.JTextField payAmount1;
    private javax.swing.JTextField rate;
    private javax.swing.JButton refresh;
    private javax.swing.JButton report;
    private javax.swing.JTextField search;
    private javax.swing.JButton tb_report;
    private javax.swing.JLabel totalAmount;
    // End of variables declaration//GEN-END:variables

public void cbLoadData(String table , String column, JComboBox cb){
    Vector v = new Vector();
    try {
        
        ResultSet rs = dbcon.SEARCH("SELECT * FROM "+table+" ");
        while(rs.next()){
            String col = rs.getString(column);
            v.add(col);
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            cb.setModel(dcm);
            
        }
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}   

}
