
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        loan = new javax.swing.JButton();
        customer_details = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER REGISTER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 420, 44));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("PHONE NO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("NAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        nic.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 330, 30));

        name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 330, 30));

        address.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 330, 30));

        phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 330, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        register.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        register.setText("REGISTER");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                registerKeyPressed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 140, 50));

        loan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loan.setText("LOAN");
        loan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });
        jPanel1.add(loan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 120, 50));

        customer_details.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customer_details.setText("CUSTOMER DETAIL");
        customer_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_detailsActionPerformed(evt);
            }
        });
        jPanel1.add(customer_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        // TODO add your handling code here:
        Loan_calculation l = new Loan_calculation();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loanActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        
        
        try {
            String ni = nic.getText();
            String na = name.getText();
            String add = address.getText();
            String ph = phone.getText();
            
            int charval = ph.length(); 
           if(charval > 8 && charval < 15){
               
               
                //JOptionPane.showMessageDialog(this,"Valid Number","DONE!",JOptionPane.INFORMATION_MESSAGE);
           }else{
                JOptionPane.showMessageDialog(this,"Invalid Number","ERROR!",JOptionPane.ERROR_MESSAGE);
               
           }
            
            dbcon.IUD("INSERT INTO customer (`nic`,`name`,`address`,`phone_no`) VALUES ('"+ni+"','"+na+"','"+add+"','"+ph+"')");
            JOptionPane.showMessageDialog(this, "Customer Registered Successfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
            nic.setText(null);
            name.setText(null);
            address.setText(null);
            phone.setText(null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerActionPerformed

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACK_SPACE  | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_V ) {
            nic.setEditable(true);
            
        }else{
            nic.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace or V","ERROR!",JOptionPane.ERROR_MESSAGE);
            nic.setText(null);
            nic.grabFocus();
        }
    }//GEN-LAST:event_nicKeyReleased

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter) | evt.getKeyCode() == KeyEvent.VK_SPACE | evt.getKeyCode() == KeyEvent.VK_PERIOD
                | evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_DELETE) {
            name.setEditable(true);
        }else{
            name.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only letters,space,dot,backspace,shift or caps lock.","ERROR!",JOptionPane.ERROR_MESSAGE);
            name.setText(null);
            name.grabFocus();
        }
    }//GEN-LAST:event_nameKeyReleased

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
        // TODO add your handling code here
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter) |Character.isDigit(letter) | evt.getKeyCode() == KeyEvent.VK_SPACE | evt.getKeyCode() == KeyEvent.VK_PERIOD
                | evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_BACK_SLASH | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK) {
            address.setEditable(true);
        }else{
            address.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only letters,space,dot,backspace,shift,back flash,num lock or caps lock.","ERROR!",JOptionPane.ERROR_MESSAGE);
            address.setText(null);
            address.grabFocus();
        }
    }//GEN-LAST:event_addressKeyReleased

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
        char digit = evt.getKeyChar();
        if(Character.isDigit(digit)| evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_EQUALS | evt.getKeyCode() == KeyEvent.VK_MINUS | evt.getKeyCode() == KeyEvent.VK_DELETE | evt.getKeyCode() == KeyEvent.VK_NUM_LOCK ) {
            phone.setEditable(true);
        }else{
            phone.setEditable(false);
            JOptionPane.showMessageDialog(this,"Use only numbers,backspace,shift,Plus or Minus keys","ERROR!",JOptionPane.ERROR_MESSAGE);
            phone.setText(null);
            phone.grabFocus();
        }
    }//GEN-LAST:event_phoneKeyReleased

    private void customer_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_detailsActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customer_detailsActionPerformed

    private void registerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerKeyPressed
        // TODO add your handling code here:
        try {
            String ni = nic.getText();
            String na = name.getText();
            String add = address.getText();
            String ph = phone.getText();
            
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                int charval = ph.length(); 
                if(charval > 8 && charval < 15){
               
               
                //JOptionPane.showMessageDialog(this,"Valid Number","DONE!",JOptionPane.INFORMATION_MESSAGE);
                }else{
                JOptionPane.showMessageDialog(this,"Invalid Number","ERROR!",JOptionPane.ERROR_MESSAGE);
               
                }
            
                    dbcon.IUD("INSERT INTO customer (`nic`,`name`,`address`,`phone_no`) VALUES ('"+ni+"','"+na+"','"+add+"','"+ph+"')");
                    JOptionPane.showMessageDialog(this, "Customer Registered Successfully","DONE!",JOptionPane.INFORMATION_MESSAGE);
            
                    nic.setText(null);
                    name.setText(null);
                    address.setText(null);
                    phone.setText(null);
            }
            
           
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton customer_details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loan;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phone;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
